# -*- coding: utf-8 -*-
"""Social Media Trend Dashboard.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/12HZoxzOEVzK0MhvY-YCMGdVSwY1h-cNI

## Resources

### Social Media Sentiment Analysis Project

**Project Overview**
This project focuses on analyzing sentiment from social media posts to understand public perception and trends. The goal is to generate synthetic social media data, perform sentiment analysis, categorize sentiment into 'Positive', 'Negative', and 'Neutral', and prepare the data for further exploration or modeling.

**Data Source**
The dataset used is a synthetic dataset generated within the notebook, simulating social media posts with timestamps, platforms, text content, and engagement metrics.

**Key Steps Performed:**
*   **Data Generation:** Creation of a synthetic dataset for social media posts, including `Timestamp`, `Platform`, `Text`, and `Engagement` fields.
*   **Sentiment Analysis:** Application of the TextBlob library to calculate a `Sentiment_Score` (polarity) for each text entry.
*   **Sentiment Categorization:** Discretization of continuous sentiment scores into categorical bins: 'Negative', 'Neutral', and 'Positive'.

**Current Status:**
The project has successfully generated a robust synthetic dataset and performed initial sentiment scoring and categorization. The data is now ready for further exploratory data analysis and visualization to understand sentiment distribution, trends, and correlations.
"""

import pandas as pd
import numpy as np
from textblob import TextBlob
import matplotlib.pyplot as plt
import seaborn as sns
from datetime import datetime, timedelta

# 1. Generate a robust synthetic dataset for guaranteed execution
np.random.seed(42)

# Create a rolling 48-hour window of timestamps
dates = [datetime.now() - timedelta(hours=np.random.randint(1, 48)) for _ in range(500)]
platforms = np.random.choice(['X (Twitter)', 'Reddit', 'LinkedIn'], 500)
engagement = np.random.randint(10, 5000, 500)

# Simulate varied social media text
texts = np.random.choice([
    "Absolutely love the new features! Game changer.",
    "This update is incredibly frustrating. Too many bugs.",
    "Just pushed a new release. Feeling optimistic.",
    "Service is down again. Unacceptable.",
    "Neutral on the new design, it's okay I guess.",
    "Best customer support experience I've ever had!",
    "I want my money back. Terrible product."
], 500)

df = pd.DataFrame({'Timestamp': dates, 'Platform': platforms, 'Text': texts, 'Engagement': engagement})

print(f"Dataset generated with {len(df)} records.")
display(df.head())

# 1. Define a function to calculate mathematical polarity
def calculate_sentiment(text):
    return TextBlob(text).sentiment.polarity

# 2. Apply the scoring engine across the entire dataset
df['Sentiment_Score'] = df['Text'].apply(calculate_sentiment)

# 3. Discretize the continuous scores into categorical bins
df['Sentiment_Category'] = pd.cut(df['Sentiment_Score'],
                                  bins=[-1.1, -0.1, 0.1, 1.1],
                                  labels=['Negative', 'Neutral', 'Positive'])

print("--- Sentiment Scoring Complete ---")
display(df[['Text', 'Sentiment_Score', 'Sentiment_Category']].head(10))