# -*- coding: utf-8 -*-
"""15EV Market Analysis Dashboard.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1a6Zb2r_5BhVtuifdXkStgYCiIgH0nCL9
"""

import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

# 1. Load the live dataset from the Washington State data portal
print("Downloading EV dataset (this may take a minute due to file size)...")
url = "https://data.wa.gov/api/views/f6w7-q2d2/rows.csv?accessType=DOWNLOAD"
df = pd.read_csv(url)

# 2. Clean column names (strip whitespace, replace spaces with underscores)
df.columns = df.columns.str.strip().str.replace(' ', '_').str.lower()

print(f"Dataset loaded successfully: {df.shape[0]} vehicles and {df.shape[1]} data points.")
display(df.head())

# Filter for modern EVs (2010 onwards) to get a clear trend
trend_df = df[df['model_year'] >= 2010]

# Group by Model Year and count the number of vehicles
yearly_adoption = trend_df.groupby('model_year').size().reset_index(name='vehicle_count')

# Render the Line Chart
plt.figure(figsize=(12, 6))
sns.lineplot(data=yearly_adoption, x='model_year', y='vehicle_count', marker='o', linewidth=2.5, color='teal')

plt.title('Electric Vehicle Adoption Trend (2010 - Present)', fontsize=16)
plt.xlabel('Model Year')
plt.ylabel('Number of Vehicles Registered')
plt.grid(True, linestyle='--', alpha=0.7)
plt.tight_layout()
plt.show()

"""## Resources

### Electric Vehicle Adoption Trend Analysis

#### Project Overview
This project analyzes the adoption trend of electric vehicles (EVs) in Washington State using publicly available data. The primary goal is to visualize how EV registrations have changed over the years, identifying periods of growth and potential insights into the market's evolution.

#### Data Source
The dataset used is the "Electric Vehicle Population Data" from the Washington State Department of Licensing, available on the Washington State data portal.

#### Key Steps Performed:
*   **Data Loading:** Loaded the live dataset directly from the Washington State data portal into a pandas DataFrame.
*   **Data Cleaning:** Cleaned column names by stripping whitespace and replacing spaces with underscores for easier access and consistency.
*   **Data Filtering:** Filtered the dataset to include only modern EVs (model year 2010 onwards) to focus on relevant trends.
*   **Data Aggregation:** Grouped the filtered data by 'model_year' to count the number of registered vehicles for each year.
*   **Data Visualization:** Generated a line chart to clearly illustrate the yearly EV adoption trend from 2010 to the present.
"""